/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulb.lisa.his.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import ulb.lisa.his.database.PersonJpaController;
import ulb.lisa.his.database.UserJpaController;
import ulb.lisa.his.model.Person;
import ulb.lisa.his.model.User;
import ulb.lisa.his.util.PasswordFactory;

/**
 *
 * @author Adrien Foucart
 */
public class CreateUserForm extends javax.swing.JFrame {
    
    private final EntityManagerFactory emfac;
    User currentUser = null;
    
    /**
     * Creates new form CreateUserForm
     * @param emfac
     */
    public CreateUserForm(EntityManagerFactory emfac){
        this(emfac, null);
    }
    
    public CreateUserForm(EntityManagerFactory emfac, User currentUser) {
        this.emfac = emfac;
        this.currentUser = currentUser;
        
        initComponents();
        
        if( currentUser != null ){
            personForm.setPerson(currentUser.getPerson());
            usernameField.setText(currentUser.getUsername());
            if( currentUser.getPassword() != null )
                passwordField.setText("------------");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        personForm = new ulb.lisa.his.view.CreatePersonForm();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        saveUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("User");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        saveUserButton.setText("Save");
        saveUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveUserButton)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(saveUserButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUserButtonActionPerformed
        try {
            Person per = personForm.getPerson();
            if( currentUser == null ) currentUser = new User();
            
            currentUser.setPerson(per);
            currentUser.setActive(true);
            currentUser.setUsername(usernameField.getText());
            if( currentUser.getIdUser() == null || !String.valueOf(passwordField.getPassword()).equals("------------")){
                String hashed = PasswordFactory.getSaltedHash(String.valueOf(passwordField.getPassword()));
                System.out.println(hashed);
                currentUser.setPassword(hashed);
            }
            
            PersonJpaController personController = new PersonJpaController(emfac);
            if( per.getIdPerson() == null )
                personController.create(per);
            else
                personController.edit(per);
            
            UserJpaController controller = new UserJpaController(emfac);
            if( currentUser.getIdUser() == null )
                controller.create(currentUser);
            else
                controller.edit(currentUser);
                
            
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(CreateUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveUserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordField;
    private ulb.lisa.his.view.CreatePersonForm personForm;
    private javax.swing.JButton saveUserButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
