/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulb.lisa.his.view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import ulb.lisa.his.database.ImagingstudyJpaController;
import ulb.lisa.his.database.PatientJpaController;
import ulb.lisa.his.database.PractitionerJpaController;
import ulb.lisa.his.database.exceptions.NonexistentEntityException;
import ulb.lisa.his.model.Imagingstudy;
import ulb.lisa.his.model.Patient;
import ulb.lisa.his.model.Person;
import ulb.lisa.his.model.Practitioner;

/**
 *
 * @author Adrien Foucart
 */
public class CreateStudyForm extends javax.swing.JFrame {
    
    private DefaultComboBoxModel<Patient> patientModel = null;
    private DefaultComboBoxModel<Practitioner> referrerModel = null;
    private DefaultComboBoxModel<Practitioner> interpreterModel = null;
    private final EntityManagerFactory emfac;
    private Imagingstudy currentStudy;
    
    /**
     * Creates new form CreateStudyForm
     * @param emfac
     */
    public CreateStudyForm(EntityManagerFactory emfac) {
        this(emfac, null, null, null);
    }
    
    public CreateStudyForm(EntityManagerFactory emfac, List<Practitioner> allPractitioners, List<Patient> allPatients) {
        this(emfac, allPractitioners, allPatients, null);
    }
    
    /**
     *
     * @param emfac
     * @param allPractitioners
     * @param allPatients
     * @param currentStudy
     */
    public CreateStudyForm(EntityManagerFactory emfac, List<Practitioner> allPractitioners, List<Patient> allPatients, Imagingstudy currentStudy) {
        this.emfac = emfac;
        this.currentStudy = currentStudy;
        
        patientModel = new DefaultComboBoxModel();
        referrerModel = new DefaultComboBoxModel();
        interpreterModel = new DefaultComboBoxModel();
        
        if( allPractitioners == null ){
            PractitionerJpaController pracController = new PractitionerJpaController(emfac);
            allPractitioners = pracController.findPractitionerEntities();
        }
        if( allPatients == null ){
            PatientJpaController patientController = new PatientJpaController(emfac);
            allPatients = patientController.findPatientEntities();
        }
                
        initComponents();
        
        Practitioner noprac = new Practitioner(-1);
        noprac.setPerson(new Person(-1));
        Patient nopat = new Patient(-1);
        nopat.setPerson(new Person(-1));
        
        fillModel(patientModel, null, allPatients, patientBox);
        fillModel(referrerModel, noprac, allPractitioners, referrerBox);
        fillModel(interpreterModel, noprac, allPractitioners, interpreterBox);
    }
    
    private void fillModel(DefaultComboBoxModel model, Object firstElement, List elements, JComboBox box){
        if( firstElement != null ) model.addElement(firstElement);
        
        for( Object e : elements ) model.addElement(e);
        
        box.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();
        reasonCodeField = new javax.swing.JTextField();
        reasonTextField = new javax.swing.JTextField();
        interpreterBox = new javax.swing.JComboBox<>();
        referrerBox = new javax.swing.JComboBox<>();
        patientBox = new javax.swing.JComboBox<>();
        uidField = new javax.swing.JTextField();
        saveStudyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("Imaging Study");

        jLabel7.setText("UID");

        jLabel8.setText("Patient");

        jLabel9.setText("Referrer");

        jLabel10.setText("Interpreter");

        jLabel11.setText("Reason");

        jLabel12.setText("Description");

        descriptionField.setColumns(20);
        descriptionField.setRows(5);
        jScrollPane2.setViewportView(descriptionField);

        reasonTextField.setEditable(false);

        saveStudyButton.setText("Save");
        saveStudyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStudyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saveStudyButton)
                        .addComponent(jLabel12)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uidField)
                    .addComponent(patientBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(referrerBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(interpreterBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reasonCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reasonTextField))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(uidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(patientBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(referrerBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(interpreterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(reasonCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(saveStudyButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveStudyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStudyButtonActionPerformed
        try {
            String uid = uidField.getText();
            Patient patient = (Patient) patientBox.getSelectedItem();
            Practitioner referrer = (Practitioner) referrerBox.getSelectedItem();
            Practitioner interpreter = (Practitioner) interpreterBox.getSelectedItem();
            int reason = Integer.valueOf(reasonCodeField.getText());
            String descr = descriptionField.getText();
            
            if( currentStudy == null ) currentStudy = new Imagingstudy();
            currentStudy.setUid(uid);
            currentStudy.setPatient(patient);
            if( referrer.getIdPractitioner()>= 0 ) currentStudy.setReferrer(referrer);
            else currentStudy.setReferrer(null);
            if( interpreter.getIdPractitioner()>= 0 ) currentStudy.setInterpreter(interpreter);
            else currentStudy.setInterpreter(null);
            currentStudy.setReason(reason);
            currentStudy.setDescription(descr);
            
            ImagingstudyJpaController controller = new ImagingstudyJpaController(emfac);
            if( currentStudy.getIdImagingStudy() == null )
                controller.create(currentStudy);
            else
                controller.edit(currentStudy);
            
            this.dispose();
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(CreateStudyForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CreateStudyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveStudyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JComboBox<String> interpreterBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> patientBox;
    private javax.swing.JTextField reasonCodeField;
    private javax.swing.JTextField reasonTextField;
    private javax.swing.JComboBox<String> referrerBox;
    private javax.swing.JButton saveStudyButton;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JTextField uidField;
    // End of variables declaration//GEN-END:variables
}
